In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch

In [2]:
print(torch.__version__)

1.13.0+cu116


In [3]:
# Crreate a 0 dimensional tensor using pytorch
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# Check dimension of scalar
scalar.ndim

0

In [5]:
# create 1 dimensional tensor
vector = torch.tensor([7])
vector

tensor([7])

In [6]:
# Check the dimension the vector
vector.ndim

1

In [7]:
vector1 = torch.tensor([7,7])
vector1

tensor([7, 7])

In [8]:
# Check dimension
vector1.ndim

1

In [9]:
# Create a matrix using torch
matrix = torch.tensor([[7,8],[9,90]])
matrix

tensor([[ 7,  8],
        [ 9, 90]])

In [10]:
# Check dimension
matrix.ndim

2

In [11]:
# check shape of the matrix
matrix.shape

torch.Size([2, 2])

In [12]:
# Create a 3 dimensional tensor 
tensor3d = torch.tensor([[[2,5,4],[9,0,8]],
                         [[2,4,2],[9,7,5]],
                         [[12,6,3],[9,8,5]]])
tensor3d

tensor([[[ 2,  5,  4],
         [ 9,  0,  8]],

        [[ 2,  4,  2],
         [ 9,  7,  5]],

        [[12,  6,  3],
         [ 9,  8,  5]]])

In [13]:
# Check dimension of the 3d tensor
tensor3d.ndim

3

In [14]:
# check the shape of the 3d tensor
tensor3d.shape

torch.Size([3, 2, 3])

##### Creating random tensor using pytorch

In [15]:
# Crate a random tensor 
rand_tensor = torch.rand(100)
rand_tensor

tensor([0.2874, 0.6138, 0.3165, 0.2375, 0.0965, 0.5033, 0.2884, 0.8378, 0.3227,
        0.7323, 0.0133, 0.6553, 0.1201, 0.0115, 0.0284, 0.9320, 0.9620, 0.4868,
        0.7842, 0.1368, 0.0265, 0.8968, 0.4135, 0.6901, 0.5430, 0.8097, 0.2277,
        0.4681, 0.1782, 0.2547, 0.2229, 0.7725, 0.4526, 0.3493, 0.1549, 0.0416,
        0.2165, 0.0863, 0.3036, 0.0907, 0.9167, 0.8672, 0.2459, 0.5961, 0.7127,
        0.1904, 0.1458, 0.5855, 0.3077, 0.6891, 0.3961, 0.1851, 0.4954, 0.6998,
        0.6157, 0.6286, 0.2708, 0.4948, 0.3871, 0.0013, 0.6031, 0.2764, 0.5700,
        0.1945, 0.9668, 0.1302, 0.0982, 0.5607, 0.6888, 0.5277, 0.3496, 0.1087,
        0.8228, 0.0972, 0.5454, 0.8269, 0.8925, 0.8651, 0.8638, 0.0679, 0.7741,
        0.4164, 0.7847, 0.6309, 0.8239, 0.4836, 0.1579, 0.8070, 0.4815, 0.4475,
        0.7075, 0.7725, 0.2045, 0.5172, 0.0066, 0.2699, 0.4801, 0.0784, 0.0084,
        0.8061])

In [16]:
rand_tensor.shape

torch.Size([100])

In [17]:
# Create a random matrix
rand_matrix = torch.rand(3,4)
rand_matrix

tensor([[0.6576, 0.0265, 0.7723, 0.3511],
        [0.5882, 0.3968, 0.8484, 0.2775],
        [0.2092, 0.8744, 0.2244, 0.7477]])

In [18]:
rand_matrix.shape,rand_matrix.ndim

(torch.Size([3, 4]), 2)

In [19]:
# Creat a random 3d tensor
rand3d_tensor = torch.rand(3,4,5)
rand3d_tensor

tensor([[[0.9350, 0.6954, 0.4342, 0.9926, 0.3578],
         [0.2012, 0.1212, 0.4175, 0.9924, 0.5677],
         [0.8704, 0.2377, 0.5802, 0.4514, 0.4848],
         [0.4413, 0.1665, 0.1929, 0.7821, 0.6093]],

        [[0.8314, 0.7806, 0.9227, 0.6498, 0.2424],
         [0.8806, 0.0808, 0.0918, 0.7832, 0.9426],
         [0.4503, 0.0682, 0.4096, 0.5624, 0.3212],
         [0.9729, 0.9171, 0.7665, 0.5525, 0.5853]],

        [[0.5139, 0.2751, 0.5701, 0.1909, 0.6666],
         [0.1128, 0.4405, 0.5185, 0.9182, 0.8240],
         [0.9787, 0.5942, 0.3774, 0.7500, 0.7927],
         [0.2338, 0.5202, 0.6339, 0.3510, 0.6315]]])

###### Zeros and ones using torch

In [20]:
# Create a zeros matrix
zeros = torch.zeros(3,4,5)
zeros

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [21]:
# Create ones using torch
ones = torch.ones(3,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [22]:
# Create a range of tensor
torch.range(0,20)   # torch.range(start,end,step)

<ipython-input-22-798caf80e3dd>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,20)   # torch.range(start,end,step)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20.])

In [23]:
torch.range(1,1000,30)

<ipython-input-23-ca599854ec87>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,1000,30)


tensor([  1.,  31.,  61.,  91., 121., 151., 181., 211., 241., 271., 301., 331.,
        361., 391., 421., 451., 481., 511., 541., 571., 601., 631., 661., 691.,
        721., 751., 781., 811., 841., 871., 901., 931., 961., 991.])

In [24]:
# also can use arange()
torch.arange(40,1000,10)

tensor([ 40,  50,  60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160, 170,
        180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310,
        320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430, 440, 450,
        460, 470, 480, 490, 500, 510, 520, 530, 540, 550, 560, 570, 580, 590,
        600, 610, 620, 630, 640, 650, 660, 670, 680, 690, 700, 710, 720, 730,
        740, 750, 760, 770, 780, 790, 800, 810, 820, 830, 840, 850, 860, 870,
        880, 890, 900, 910, 920, 930, 940, 950, 960, 970, 980, 990])

#### Tensor datatypes

In [25]:
# Float 32 tensor
float_32_tensor = torch.tensor([2.,2.,5.],dtype = None)
float_32_tensor

tensor([2., 2., 5.])

In [26]:
float_32_tensor.dtype  # defualt is float32 

torch.float32

In [27]:
# Create float 16 dtype tensor
float_16_tensor = torch.tensor([1.,6.,8.],dtype = torch.float16)
float_16_tensor

tensor([1., 6., 8.], dtype=torch.float16)

In [28]:
torch.tensor([3,5,6,5],dtype = None  # what datatype
                      , device = None # what device is your tensor on
                      , requires_grad = False) # whether on not to track gradients

tensor([3, 5, 6, 5])

In [29]:
# Lets do some operation on different datatypes
float_16_tensor*float_32_tensor  # It works but keep in mind while training neural network some times operation on different datatype create issue

tensor([ 2., 12., 40.])

#### Getting information from tensors

In [30]:
some_tensor = torch.rand(4,3)
some_tensor

tensor([[0.0446, 0.8834, 0.5868],
        [0.6084, 0.9763, 0.7573],
        [0.7298, 0.3699, 0.6715],
        [0.7982, 0.5517, 0.5735]])

In [31]:
print("Device some_tesor is  on:",some_tensor.device)

Device some_tesor is  on: cpu


##### Manipulating tensor (tensor operations)

In [32]:
matrix

tensor([[ 7,  8],
        [ 9, 90]])

In [33]:
# Add 10 to each element
matrix + 10

tensor([[ 17,  18],
        [ 19, 100]])

In [34]:
# Substract 10 to each element
matrix - 10

tensor([[-3, -2],
        [-1, 80]])

In [35]:
# Multiply 10 to each element
matrix* 10

tensor([[ 70,  80],
        [ 90, 900]])

In [36]:
# divide each element by 10
matrix/10

tensor([[0.7000, 0.8000],
        [0.9000, 9.0000]])

In [37]:
# use built in add function to add 
torch.add(matrix,10)

tensor([[ 17,  18],
        [ 19, 100]])

In [38]:
# use built in multiply function to add 
torch.mul(matrix,10)

tensor([[ 70,  80],
        [ 90, 900]])

In [39]:
# Matrix multiplication
torch.matmul(matrix,matrix)

tensor([[ 121,  776],
        [ 873, 8172]])

In [40]:
# we can use mm as alias of matmul
torch.mm(matrix,matrix)

tensor([[ 121,  776],
        [ 873, 8172]])

In [41]:
# we can also use @ for matrix multiplication
matrix @ matrix

tensor([[ 121,  776],
        [ 873, 8172]])

In [42]:
print("the original matrix is:",matrix)
print("the transpose of the matrix is:",matrix.T)

the original matrix is: tensor([[ 7,  8],
        [ 9, 90]])
the transpose of the matrix is: tensor([[ 7,  9],
        [ 8, 90]])


In [43]:
# Create a large tensor
large_tensor = torch.rand(1000)
large_tensor

tensor([2.0668e-01, 3.3295e-01, 8.5895e-01, 1.1227e-01, 7.0380e-01, 2.2801e-01,
        2.0874e-01, 3.8434e-02, 8.1672e-01, 4.2029e-01, 2.8112e-01, 2.5341e-01,
        6.5958e-01, 3.8044e-01, 3.9557e-01, 2.7752e-02, 6.5343e-01, 5.2375e-01,
        8.8477e-01, 5.9410e-01, 7.0929e-02, 3.3705e-01, 6.2528e-01, 2.5307e-01,
        7.4088e-01, 1.9248e-01, 4.8283e-01, 6.0071e-01, 8.2310e-01, 2.4058e-01,
        1.3678e-01, 3.6254e-01, 7.3139e-01, 8.2906e-01, 1.7822e-01, 5.2964e-01,
        5.0637e-01, 4.1066e-01, 4.1939e-01, 1.7432e-01, 4.8337e-01, 6.8879e-01,
        3.4498e-01, 1.4288e-02, 2.0802e-01, 6.9470e-01, 8.1917e-01, 5.9593e-01,
        6.8386e-01, 2.1935e-01, 8.4656e-01, 7.7378e-01, 5.5859e-01, 3.6284e-01,
        1.0241e-01, 7.2433e-01, 9.4152e-01, 5.4634e-01, 5.0226e-01, 8.1961e-01,
        5.6302e-01, 4.7113e-01, 4.1844e-01, 3.1613e-01, 4.7011e-01, 3.8904e-01,
        8.5291e-01, 3.8447e-01, 2.1123e-01, 8.9168e-01, 2.7100e-01, 9.6880e-01,
        1.7792e-01, 3.9054e-01, 7.8562e-

In [44]:
# Find the minimum value
large_tensor.min()

tensor(0.0008)

In [45]:
# find the maximum value
large_tensor.max()

tensor(0.9992)

In [46]:
# Find the sum of elements
large_tensor.sum()

tensor(506.5600)

In [47]:
# Find the mean of the tensor
large_tensor.mean()

tensor(0.5066)

In [48]:
# Creat an int dtype tensor and apply those functions
int_large_tensor = torch.arange(1,1000,10)
int_large_tensor

tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
        141, 151, 161, 171, 181, 191, 201, 211, 221, 231, 241, 251, 261, 271,
        281, 291, 301, 311, 321, 331, 341, 351, 361, 371, 381, 391, 401, 411,
        421, 431, 441, 451, 461, 471, 481, 491, 501, 511, 521, 531, 541, 551,
        561, 571, 581, 591, 601, 611, 621, 631, 641, 651, 661, 671, 681, 691,
        701, 711, 721, 731, 741, 751, 761, 771, 781, 791, 801, 811, 821, 831,
        841, 851, 861, 871, 881, 891, 901, 911, 921, 931, 941, 951, 961, 971,
        981, 991])

In [49]:
int_large_tensor.dtype

torch.int64

In [50]:
# Find the minimum value
int_large_tensor.min()

tensor(1)

In [51]:
# find the maximum value
int_large_tensor.max()

tensor(991)

In [52]:
# Find the sum of elements
int_large_tensor.sum()

tensor(49600)

In [54]:
# Find the mean of the tensor
int_large_tensor.mean()  # oah why this error?

RuntimeError: ignored

#### It looks like mean() function works for float and complex dtype only but it got int (Long) dtype

In [ ]:
# Lets change the dtype of the tensor try that function
int_large_tensor.type(torch.float32).mean()

#### Finding positional max and positional min 

In [ ]:
large_tensor

In [ ]:
# Find the index of max number in the tensor
torch.argmax(large_tensor),large_tensor.argmax()

In [55]:
# Find the index of min number in the tensor
torch.argmin(large_tensor),large_tensor.argmin()

(tensor(113), tensor(113))

#### Reshaping,stacking,squeezing and unsqueezing tensor

In [56]:
x = torch.arange(10,100,5)
x

tensor([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [57]:
x.shape

torch.Size([18])

In [58]:
# Reshape x
x.reshape(6,3)

tensor([[10, 15, 20],
        [25, 30, 35],
        [40, 45, 50],
        [55, 60, 65],
        [70, 75, 80],
        [85, 90, 95]])

In [59]:
# change the view
z = x.view(6,3) # view is same as reshape but this shares the memory
z

tensor([[10, 15, 20],
        [25, 30, 35],
        [40, 45, 50],
        [55, 60, 65],
        [70, 75, 80],
        [85, 90, 95]])

In [60]:
# changing z changes x
z[0] = -15
x  # see -15 is appearing in x

tensor([-15, -15, -15,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,  75,
         80,  85,  90,  95])

In [61]:
# stack tensors on top of each other
z_stacked = torch.stack([z,z,z,z],dim = 0)
z_stacked,z_stacked.ndim

(tensor([[[-15, -15, -15],
          [ 25,  30,  35],
          [ 40,  45,  50],
          [ 55,  60,  65],
          [ 70,  75,  80],
          [ 85,  90,  95]],
 
         [[-15, -15, -15],
          [ 25,  30,  35],
          [ 40,  45,  50],
          [ 55,  60,  65],
          [ 70,  75,  80],
          [ 85,  90,  95]],
 
         [[-15, -15, -15],
          [ 25,  30,  35],
          [ 40,  45,  50],
          [ 55,  60,  65],
          [ 70,  75,  80],
          [ 85,  90,  95]],
 
         [[-15, -15, -15],
          [ 25,  30,  35],
          [ 40,  45,  50],
          [ 55,  60,  65],
          [ 70,  75,  80],
          [ 85,  90,  95]]]), 3)

In [62]:
# troch.squeeze() removes all single dimensions form tensor
z_reshaped = z.reshape(1,6,3)

In [63]:
z_reshaped.shape

torch.Size([1, 6, 3])

In [64]:
# remove single dimesnion form z
z_squeezed = z.squeeze()

In [65]:
z_squeezed.shape  # See single dimension has been removed

torch.Size([6, 3])

In [66]:
# torch.unsqueeze() add a single dimension to target tensor at desired diemsnion
z_unsqueezed = z_squeezed.unsqueeze(dim = 0)
z_unsqueezed,z_unsqueezed.shape

(tensor([[[-15, -15, -15],
          [ 25,  30,  35],
          [ 40,  45,  50],
          [ 55,  60,  65],
          [ 70,  75,  80],
          [ 85,  90,  95]]]), torch.Size([1, 6, 3]))

In [67]:
z_unsqueezed = z_squeezed.unsqueeze(dim = 1)
z_unsqueezed,z_unsqueezed.shape

(tensor([[[-15, -15, -15]],
 
         [[ 25,  30,  35]],
 
         [[ 40,  45,  50]],
 
         [[ 55,  60,  65]],
 
         [[ 70,  75,  80]],
 
         [[ 85,  90,  95]]]), torch.Size([6, 1, 3]))

In [68]:
# torch.permute rearrange the rarrange the dimension of target tensor in specified order
X_original = torch.rand(size=(224,228,3))
X_permuted = X_original.permute(2,0,1)  # Shifts axis 0 -> 1, 1->2, and 2->0. Remember it refers to same memory so any change in either will appear in both
print(f"The shape of original tensor is: {X_original.shape}")
print(f"The shape of permuted tensor is:{X_permuted.shape}")

The shape of original tensor is: torch.Size([224, 228, 3])
The shape of permuted tensor is:torch.Size([3, 224, 228])


In [69]:
X_original[0,0,0] = 2435
X_original[0,0,0],X_permuted[0,0,0]

(tensor(2435.), tensor(2435.))

##### Indexing in pytorch
Indexing in pytorch is the same as in numpy

In [70]:
# Create a random tensor
random_tensor = torch.arange(0,10).reshape(2,5)
random_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [71]:
# Acces the whole element of first row
random_tensor[0]

tensor([0, 1, 2, 3, 4])

In [72]:
# Access 3,4,8,9 from the tensor
random_tensor[:,3:]

tensor([[3, 4],
        [8, 9]])

In [73]:
# Access 1,3,6,8
random_tensor[:,1:4:2]

tensor([[1, 3],
        [6, 8]])

In [74]:
# creae a 3d random tensor
random_tensor = torch.range(1,9).reshape(1,3,3)
random_tensor

<ipython-input-74-b6f8585da327>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  random_tensor = torch.range(1,9).reshape(1,3,3)


tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [75]:
# Access 5,6,8,9
random_tensor[0,1:,1:]

tensor([[5., 6.],
        [8., 9.]])

In [76]:
# Access 3,6,9
random_tensor[:,:,2:]

tensor([[[3.],
         [6.],
         [9.]]])

In [77]:
# Access 7,8,9
random_tensor[0,-1]

tensor([7., 8., 9.])

In [78]:
# We can use ":" to select all elements of a target didmension
random_tensor[:,1]

tensor([[4., 5., 6.]])

In [79]:
# Get all values of 0th and 1st dimension but only index 1 of second dimension
random_tensor[:,:,1]

tensor([[2., 5., 8.]])

In [80]:
# Get index 0 of 0th and 1st dimension and all values of the second dimension
random_tensor[0,0,:]

tensor([1., 2., 3.])

In [81]:
# access 9 form the random tensor
random_tensor[0,2,-1]

tensor(9.)

Pytorch and Numpy
Numpy is a popular scientific python numerical computing library and because of this, putorch has functionality to interact with it.
* Data in Numpy, want in PyTorch -> `torch.from_numpy(ndarray)`
* PyTorch tensor to numpy array -> `torch.Tensor.numpy()`

In [82]:
# Numpy array to tensor
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning: When converting from numpy to pytorch, puytorch reflects numpy default datatype float 64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [83]:
array.dtype

dtype('float64')

In [84]:
tensor.dtype

torch.float64

In [85]:
torch.arange(1.0,8.0).dtype

torch.float32

In [86]:
# Change the value of array
array = array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [87]:
# Tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy() # Notice that numpy has pytorch default datatype float32
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [88]:
# change the tensor what happens to numpy_tensro?
tensor = tensor + 1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

PyTorch Reproducibility
To reduce the randomness there is a concept ** random seed**. Essentially what the random seed does it picks consistent random value.

In [89]:
torch.rand(3,3)

tensor([[0.6960, 0.1711, 0.0223],
        [0.7595, 0.2575, 0.7002],
        [0.0977, 0.6600, 0.3059]])

In [90]:
# create two random tensor
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2123, 0.4253, 0.2744, 0.1903],
        [0.4434, 0.4072, 0.9908, 0.8689],
        [0.6074, 0.7446, 0.8534, 0.3491]])
tensor([[0.8645, 0.9914, 0.7463, 0.5761],
        [0.4241, 0.1114, 0.7628, 0.9913],
        [0.9916, 0.1494, 0.3837, 0.9392]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [91]:
# Lets make some random tensor but reproducible
# Set the random ssed
Random_Seed = 42
torch.manual_seed(Random_Seed)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(Random_Seed)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [92]:
!nvidia-smi

Sat Dec 24 07:13:37 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   70C    P0    30W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [93]:
# Check GPU acces with pytorch
torch.cuda.is_available()  # True means we have accese to cuda gpu

True

In [95]:
# Set up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [96]:
# Count the number of gpu
torch.cuda.device_count()

1

PyTorch is capable of runnig on gpu and cpu so it is better to setup device adgnostic code
E.g. Run on gpu if it is available otherwise run on cpu

In [97]:
# Create a tensor default on cpu
tensor = torch.tensor([1,3,4])
print(tensor,tensor.device)

tensor([1, 3, 4]) cpu


In [98]:
# Move tensor to gpu if it is avialable
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 3, 4], device='cuda:0')

In [99]:
## Move tensor back to cpu
tensor_on_gpu.numpy() # This throw an error becuase numpy doesnt work on gpu

TypeError: ignored

In [102]:
# First set the tensor on cpu to use it in numpy
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 3, 4])

In [103]:
# Note that tensor on gpu is unchanged
tensor_on_gpu

tensor([1, 3, 4], device='cuda:0')